### ISSUE TITLE
ETA on english version

### ISSUE THREAD

**Issue by mxood001** [huanghanzhilian/exercise-full-next#1]
First of all, amazing project, and very generous of you to make it open source, I want to use to learn best practices , I was wondering you metnioned you are working on a english version, Is there an ETA, or is it currently on the back burner.

**Comment by huanghanzhilian** [comment]
@mxood001 Within a month, I will work hard to implement the English version. If you are interested, you can join us.

**Comment by mxood001** [comment]
thank you appreciate it, i will look into it after the translation and see i could help out, but few months down the road is when i have intention to dabble into it. will definitely, and see if i could provide input as well when i start.
