### ISSUE TITLE
Update the package to your application name 

### ISSUE THREAD

**Issue by softwarenacho** [huanghanzhilian/exercise-full-next#9]
https://github.com/huanghanzhilian/c-shopping/blob/0b2b221213770c08e1b0d7dbb510fee62c101278/package.json#L2

Wanted to open this issue to reach out,  I'm taking a look to the code and noticed this first, is small thing but it will be better if you have the app name here

I wanted to reach to offer my help, I can help you make this project an installable PWA if you are interested, it can help the concurrent users access more comfortably and in the future to reach app stores

I also have experience with performance so will like to take a look at that too

I will comment in this issue any suggestion I can find in the current code

This is a great work! ⭐

**Comment by softwarenacho** [comment]
@huanghanzhilian this are my suggestions let me know if I can help you with anything

1. **TypeScript**: 
   - **Explanation**: Adds static typing to JavaScript, helping catch errors early during development and improving code quality and maintainability.

2. **PWA (Progressive Web App)**:
   - **Explanation**: Enhances the app with features like offline support, push notifications, and improved loading times, providing a more native app-like experience.

3. **Internalization (i18n)**:
   - **Explanation**: Makes the app accessible to users speaking different languages by supporting multiple languages, which can expand the user base and improve user experience.

4. **Local Storage Cache**:
   - **Explanation**: Stores frequently accessed data locally, reducing load times and improving app performance, especially in scenarios with limited or intermittent network connectivity.

5. **Page Jumps**:
   - **Explanation**: Ensures smooth scrolling and navigation within the app, improving user experience by reducing abrupt transitions and making navigation more intuitive.

6. **Images Zoom**:
   - **Explanation**: Allows users to zoom in on images, enhancing usability and accessibility, especially for detailed images where closer inspection is needed.

7. **User Select None on Clickable Elements**:
   - **Explanation**: Prevents text selection on interactive elements like buttons and links, providing a cleaner and more polished user interface.

8. **Accessibility (a11y)**:
   - **Explanation**: Ensures the app is usable by people with disabilities, improving inclusivity and complying with accessibility standards and guidelines.

9. **Mobile Move Up When Keyboard Opens**:
   - **Explanation**: Adjusts the viewport when the keyboard opens on mobile devices, preventing form fields from being obscured and ensuring a seamless user experience on mobile.

**Comment by huanghanzhilian** [comment]
> @huanghanzhilian this are my suggestions let me know if I can help you with anything
> 
> 1. **TypeScript**:
>    
>    * **Explanation**: Adds static typing to JavaScript, helping catch errors early during development and improving code quality and maintainability.
> 2. **PWA (Progressive Web App)**:
>    
>    * **Explanation**: Enhances the app with features like offline support, push notifications, and improved loading times, providing a more native app-like experience.
> 3. **Internalization (i18n)**:
>    
>    * **Explanation**: Makes the app accessible to users speaking different languages by supporting multiple languages, which can expand the user base and improve user experience.
> 4. **Local Storage Cache**:
>    
>    * **Explanation**: Stores frequently accessed data locally, reducing load times and improving app performance, especially in scenarios with limited or intermittent network connectivity.
> 5. **Page Jumps**:
>    
>    * **Explanation**: Ensures smooth scrolling and navigation within the app, improving user experience by reducing abrupt transitions and making navigation more intuitive.
> 6. **Images Zoom**:
>    
>    * **Explanation**: Allows users to zoom in on images, enhancing usability and accessibility, especially for detailed images where closer inspection is needed.
> 7. **User Select None on Clickable Elements**:
>    
>    * **Explanation**: Prevents text selection on interactive elements like buttons and links, providing a cleaner and more polished user interface.
> 8. **Accessibility (a11y)**:
>    
>    * **Explanation**: Ensures the app is usable by people with disabilities, improving inclusivity and complying with accessibility standards and guidelines.
> 9. **Mobile Move Up When Keyboard Opens**:
>    
>    * **Explanation**: Adjusts the viewport when the keyboard opens on mobile devices, preventing form fields from being obscured and ensuring a seamless user experience on mobile.

Thank you very much for your serious comments, which are very helpful to me. Some of the questions you raised are exactly what I want to do, but because I am alone and have time at work, I cannot complete them quickly. If you are interested, I welcome you to join us and improve this project together.

**Comment by huanghanzhilian** [comment]
> https://github.com/huanghanzhilian/c-shopping/blob/0b2b221213770c08e1b0d7dbb510fee62c101278/package.json#L2
> 
> Wanted to open this issue to reach out, I'm taking a look to the code and noticed this first, is small thing but it will be better if you have the app name here
> 
> I wanted to reach to offer my help, I can help you make this project an installable PWA if you are interested, it can help the concurrent users access more comfortably and in the future to reach app stores
> 
> I also have experience with performance so will like to take a look at that too
> 
> I will comment in this issue any suggestion I can find in the current code
> 
> This is a great work! ⭐

I have corrected this problem, thank you for helping me correct it. I welcome you to join us. We can have more communication together.

**Comment by softwarenacho** [comment]
Great work!
